import Head from "next/head";
import { useContext } from "react";
import { AuthContext } from "../utils/authContext";
import { trpc } from "../utils/trpc";
export default function Home() {
  const authCtx = useContext(AuthContext);
  const someData = trpc.plant.all.useQuery();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>next App</main>
    </>
  );
}
