export const category = {
  flowers: [
    "alyssum",
    "aster",
    "azalea",
    "barberton daisy",
    "begonia",
    "carnation",
    "china aster",
    "chrysanthemum",
    "daffodil",
    "freesia",
    "geranium",
    "gerbera daisy",
    "gladiolus",
    "iris",
    "marigold",
    "nasturtium",
    "pansy",
    "peony",
    "primrose",
    "rhododendron",
    "snapdragon",
    "sunflower",
    "sweet pea",
    "transvaal daisy",
    "various flowers",
    "verbena",
    "violet",
    "zinnia",
  ],
  fruits: [
    "almond",
    "apple",
    "apricot",
    "pear",
    "plum",
    "prune",
    "quince",
    "stone fruit",
    "strawberry",
    "various fruits and nuts",
    "walnut",
  ],
  lawns: [
    "all lawn grasses",
    "annual bluegrass",
    "bentgrasses",
    "bermudagrass",
    "bluegrass",
    "dichondra",
    "fescues",
    "fine fescues",
    "kentucky bluegrass",
    "kikuyugrass",
    "ryegrasses",
    "seashore paspalum",
    "st. augustine grass",
    "zoysiagrass",
  ],
  trees: [
    "ash",
    "aspen",
    "boxwood",
    "buckthorn",
    "california hazel",
    "camellia",
    "coffeeberry",
    "conifers",
    "cottonwood",
    "crape myrtle",
    "cryptomeria",
    "dogwood",
    "douglas fir",
    "elm",
    "filbert",
    "forsythia",
    "hackberry",
    "hazlenut",
    "hemlock",
    "juniper",
    "laurel",
    "live oak",
    "london plane tree",
    "oak",
    "oleander",
    "olive tree",
    "palm tree",
    "pine",
    "poplar",
    "redberry",
    "rhamnus",
    "rose",
    "sweet gum/liquidambar",
    "sycamore",
    "various trees and shrubs",
  ],
  vegs: [
    "artichoke",
    "asparagus",
    "avocado",
    "beans",
    "beet",
    "black-eyed pea",
    "broccoli",
    "brussel sprouts",
    "cabbage",
    "cantaloupe",
    "carrot",
    "cauliflower",
    "cole crops",
    "corn",
    "cucumber",
    "cucurbits",
    "eggplant",
    "endive",
    "lettuce",
    "melon",
    "okra",
    "onions and garlic",
    "parsley",
    "parsnip",
    "pea",
    "pepper",
    "potato",
    "pumpkin",
    "radicchio",
    "radish",
    "spinach",
    "squash",
    "tomatillo",
    "tomato",
    "turnip",
    "various vegetables and melons",
    "watermelon",
  ],
};

export const allCat = [...category.flowers, ...category.fruits, ...category.lawns, ...category.trees, ...category.vegs];

export const alias = {
  "onions and garlic": ["onions", "garlic"],
  "stone fruit": [
    "coconut",
    "olive",
    "plum",
    "peach",
    "plum",
    "cherry",
    "nectarine",
    "apricot",
    "mango",
    "lychee",
    "raspberry",
    "blackberry",
    "mulberry",
    "date",
  ],
  "london plane tree": ["london plane"],
  "california hazel": ["beaked hazelnut"],
  "barberton daisy": ["daisy"],
  "gerbera daisy": ["daisy"],
  "transvaal daisy": ["daisy"],
};

export const TracheophytaClass = {
  Polypodiopsida: ["lawns"],
  Magnoliopsida: ["flowers", "fruits", "vegs"],
  Liliopsida: ["flowers", "fruits", "vegs"],
  Pinopsida: ["trees"],
  Lycopodiopsida: ["trees"],
  Gnetopsida: ["trees"],
  Cycadopsida: ["trees"],
};

export const MagnoliopsidaOrder = {
  Lamiales: ["flowers"],
  Oxalidales: ["flowers"],
  Ranunculales: ["flowers"],
  Boraginales: ["flowers"],
  Ericales: ["flowers", "fruits"],
  Nymphaeales: ["flowers"],
  Malpighiales: ["flowers", "fruits"],
  Piperales: ["flowers", "fruits"],
  Fabales: ["flowers", "vegs"],
  Caryophyllales: ["flowers", "vegs"],
  Saxifragales: ["flowers", "fruit"],
  Dipsacales: ["flowers", "fruit"],
  Gentianales: ["flowers"],
  Brassicales: ["flowers", "fruits", "vegs"],
  Rosales: ["flowers"],
  Geraniales: ["flowers"],
  Apiales: ["flowers", "vegs"],
  Fagales: ["trees"],
  Garryales: ["flowers"],
  Malvales: ["flowers", "fruit"],
  Solanales: ["flowers", "vegs"],
  Sapindales: ["trees", "fruit", "vegs"],
  Cornales: ["flowers"],
  Myrtales: ["flowers", "fruit"],
  Vitales: ["fruit"],
  Santalales: ["trees"],
  Cucurbitales: ["fruit", "vegs"],
  Laurales: ["trees", "vegs"],
  Zygophyllales: ["trees", "flowers"],
  Celastrales: ["trees", "flowers"],
  Proteales: ["flowers"],
  Magnoliales: ["flowers", "fruits"],
};
