export const category = {
  flower: [
    "alyssum",
    "aster",
    "azalea",
    "barberton daisy",
    "begonia",
    "carnation",
    "china aster",
    "chrysanthemum",
    "daffodil",
    "freesia",
    "geranium",
    "gerbera daisy",
    "gladiolus",
    "iris",
    "marigold",
    "nasturtium",
    "pansy",
    "peony",
    "primrose",
    "rhododendron",
    "snapdragon",
    "sunflower",
    "sweet pea",
    "transvaal daisy",
    "various flowers",
    "verbena",
    "violet",
    "zinnia",
  ],
  frutis: [
    "almond",
    "apple",
    "apricot",
    "pear",
    "plum",
    "prune",
    "quince",
    "stone fruit",
    "strawberry",
    "various fruits and nuts",
    "walnut",
  ],
  lawns: [
    "all lawn grasses",
    "annual bluegrass",
    "bentgrasses",
    "bermudagrass",
    "bluegrass",
    "dichondra",
    "fescues",
    "fine fescues",
    "kentucky bluegrass",
    "kikuyugrass",
    "ryegrasses",
    "seashore paspalum",
    "st. augustine grass",
    "zoysiagrass",
  ],
  trees: [
    "ash",
    "aspen",
    "boxwood",
    "buckthorn",
    "california hazel",
    "camellia",
    "coffeeberry",
    "conifers",
    "cottonwood",
    "crape myrtle",
    "cryptomeria",
    "dogwood",
    "douglas fir",
    "elm",
    "filbert",
    "forsythia",
    "hackberry",
    "hazlenut",
    "hemlock",
    "juniper",
    "laurel",
    "live oak",
    "london plane tree",
    "oak",
    "oleander",
    "olive tree",
    "palm tree",
    "pine",
    "poplar",
    "redberry",
    "rhamnus",
    "rose",
    "sweet gum/liquidambar",
    "sycamore",
    "various trees and shrubs",
  ],
  vegs: [
    "artichoke",
    "asparagus",
    "avocado",
    "beans",
    "beet",
    "black-eyed pea",
    "broccoli",
    "brussel sprouts",
    "cabbage",
    "cantaloupe",
    "carrot",
    "cauliflower",
    "cole crops",
    "corn",
    "cucumber",
    "cucurbits",
    "eggplant",
    "endive",
    "lettuce",
    "melon",
    "okra",
    "onions and garlic",
    "parsley",
    "parsnip",
    "pea",
    "pepper",
    "potato",
    "pumpkin",
    "radicchio",
    "radish",
    "spinach",
    "squash",
    "tomatillo",
    "tomato",
    "turnip",
    "various vegetables and melons",
    "watermelon",
  ],
};

export const catDiv = {
  flower: ["Magnoliopsida", "Liliopsida"],
  lawns: ["Polypodiopsida"],
  trees: ["pinopsida", "Lycopodiopsida"],
};
